# Generated by Django 3.0.6 on 2021-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_quizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=50),
        ),
    ]
