# Generated by Django 3.0.6 on 2021-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_auto_20210122_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard')], max_length=50),
        ),
    ]
