# Generated by Django 3.0.6 on 2021-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0004_auto_20210122_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questions_type',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard')], default='easy', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(default='', max_length=255),
        ),
    ]
