# Generated by Django 3.0.6 on 2021-01-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0006_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('messages', models.CharField(default='', max_length=200)),
                ('exam_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quizer')),
            ],
        ),
    ]
