# Generated by Django 3.0.6 on 2021-01-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='exam_no',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
