# Generated by Django 3.0.6 on 2021-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0008_auto_20210123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
