# Generated by Django 3.0.6 on 2021-01-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0010_quiztaker_usersanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAnswer',
        ),
    ]
