# Generated by Django 3.0.6 on 2021-01-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0013_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(default='', max_length=255)),
                ('option1', models.CharField(default=' ', max_length=255)),
                ('option2', models.CharField(default=' ', max_length=255)),
                ('option3', models.CharField(default=' ', max_length=255)),
                ('option4', models.CharField(default=' ', max_length=255)),
                ('correct_option', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('difficulty', models.IntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='quiz_api.Quiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
