# Generated by Django 3.0.6 on 2021-01-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0014_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='question_attemted',
            field=models.IntegerField(default=0),
        ),
    ]
