# Generated by Django 3.0.6 on 2021-01-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0015_quiztaker_question_attemted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiztaker',
            unique_together={('user', 'quiz')},
        ),
    ]
