# Generated by Django 3.0.6 on 2021-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0017_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='level_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[('easy', 1), ('medium', 2), ('hard', 3)], default=1),
        ),
    ]
