# Generated by Django 3.0.6 on 2021-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0018_auto_20210124_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')], default=1),
        ),
    ]
