# Generated by Django 3.0.6 on 2021-01-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0019_auto_20210124_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
