# Generated by Django 3.0.6 on 2021-01-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0020_auto_20210125_0934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'quiz')},
        ),
    ]
