# Generated by Django 3.0.3 on 2021-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0021_auto_20210125_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='level_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='level_2',
            field=models.IntegerField(default=0),
        ),
    ]
